version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway
      - service1-1
      - service1-2
      - service2-1
      - service2-2
      - service3-1
      - service3-2

  api-gateway:
    build:
      context: ./api-gateway
    environment:
      - NODE_ENV=development

  service1-1:
    build:
      context: ./service1
    environment:
      - NODE_ENV=development

  service1-2:
    build:
      context: ./service1
    environment:
      - NODE_ENV=development

  service2-1:
    build:
      context: ./service2
    environment:
      - NODE_ENV=development

  service2-2:
    build:
      context: ./service2
    environment:
      - NODE_ENV=development

  service3-1:
    build:
      context: ./service3
    environment:
      - NODE_ENV=development

  service3-2:
    build:
      context: ./service3
    environment:
      - NODE_ENV=development




# version: '3.8'
# services:
#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - api-gateway
#       - service1
#       - service2
#       - service3

#   api-gateway:
#     build:
#       context: ./api-gateway
#     environment:
#       - NODE_ENV=development

#   service1:
#     build:
#       context: ./service1
#     environment:
#       - NODE_ENV=development

#   service2:
#     build:
#       context: ./service2
#     environment:
#       - NODE_ENV=development

#   service3:
#     build:
#       context: ./service3
#     environment:
#       - NODE_ENV=development

# version: '3.8'

# services:
#   nginx:
#     build:
#       context: ./nginx
#     ports:
#       - "80:80"
#     depends_on:
#       - api-gateway
#       - service1
#       - service2
#       - service3
#     networks:
#       - app-network

#   api-gateway:
#     build:
#       context: ./api-gateway
#     environment:
#       - NODE_ENV=development
#     networks:
#       - app-network

#   service1:
#     build:
#       context: ./service1
#     environment:
#       - NODE_ENV=development
#     networks:
#       - app-network

#   service2:
#     build:
#       context: ./service2
#     environment:
#       - NODE_ENV=development
#     networks:
#       - app-network

#   service3:
#     build:
#       context: ./service3
#     environment:
#       - NODE_ENV=development
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
