version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "1100:1100"
    depends_on:
      - service1
      - service2
      - service3

  service1:
    build: ./service1
    ports:
      - "100:100"

  service2:
    build: ./service2
    ports:
      - "200:200"


  service3:
    build: ./service3
    ports:
      - "300:300"

