version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway
      - service1-1
      - service1-2
      - service2-1
      - service2-2
      - service3-1
      - service3-2

  api-gateway:
    build:
      context: ./api-gateway
    environment:
      - NODE_ENV=development

  service-call-gateway:
    build:
      context: ./service-call-gateway
    environment:
      - NODE_ENV=development

  service1-1:
    build:
      context: ./service1
    environment:
      - NODE_ENV=development

  service1-2:
    build:
      context: ./service1
    environment:
      - NODE_ENV=development

  service2-1:
    build:
      context: ./service2
    environment:
      - NODE_ENV=development

  service2-2:
    build:
      context: ./service2
    environment:
      - NODE_ENV=development

  service3-1:
    build:
      context: ./service3
    environment:
      - NODE_ENV=development

  service3-2:
    build:
      context: ./service3
    environment:
      - NODE_ENV=development

  umbra:
    build:
      context: ./umbra
    environment:
      - NODE_ENV=development

  iceye:
    build:
      context: ./iceye
    environment:
      - NODE_ENV=development

  planet:
    build:
      context: ./planet
    environment:
      - NODE_ENV=development