version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway
      - service1
      - service2
      - service3
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  service1:
    build:
      context: ./service1
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  service2:
    build:
      context: ./service2
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  service3:
    build:
      context: ./service3
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
