FROM node:20.12.2

# Set the working directory in the container
WORKDIR /planet

# Copy package.json and package-lock.json (if exists) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server application code
COPY . .

EXPOSE 8000

# Command to run the server
CMD ["npm", "run", "start:dev"]