version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service1
      - service2
      - service3

  service1:
    build: ./service1
    container_name: service1
    ports:
      - "100:100"

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "200:200"

  service3:
    build: ./service3
    container_name: service3
    ports:
      - "300:300"
